debug: true
server:
  port: 8085
  servlet:
    context-path: /citizen
    error:
      whitelabel:
        enabled: true
    session:
      timeout: 10m
    multipart:
      max-file-size: 20MB
      max-request-size: 25MB
      enabled: false
spring:
  application:
    name: '@project.name@'
    version: '@project.version@'
    uploadDirectory: ${user:home}/citizen
    imageSize: 300
  jmx:
    default-domain: mm
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/ikm"
    username: ${DB_USER:postgres}
    password: ${DB_PASS:pass}


springdoc:
  cache:
    disabled: true
  api-docs:
    path: /api-docs
  model-converters:
    pageable-converter:
      enabled: true
  writer-with-default-pretty-printer: true
  swagger-ui:
    apisSorter: alpha
    operationsSorter: alpha
    disable-swagger-default-url: true

logging:
  level:
    root: INFO
